## Importing Necessary

In [1]:
import os 
import math
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.experimental import enable_iterative_imputer

# for processing and feature engineering 

from sklearn.impute import (
    SimpleImputer,
    KNNImputer
)

from sklearn.feature_selection import (
    SelectKBest,
    SelectPercentile,
    RFE,
    RFECV,
    VarianceThreshold
)


from sklearn.preprocessing import(
    OneHotEncoder,
    MinMaxScaler,
    StandardScaler,
    RobustScaler,
    Normalizer,
    PolynomialFeatures,
    OrdinalEncoder,
    LabelEncoder,
    KBinsDiscretizer,
    FunctionTransformer
)

# Model Selection and Evaluation


from sklearn.model_selection import (
    train_test_split,
    cross_val_predict,
    cross_val_score,
    GridSearchCV,
    RandomizedSearchCV,
    StratifiedKFold,
    KFold,
    cross_validate
)


from sklearn.metrics import (
    accuracy_score,
    precision_recall_curve,
    roc_auc_score,
    mean_absolute_error,
    mean_absolute_percentage_error,
    root_mean_squared_error,
    mean_squared_error,
    confusion_matrix,
    r2_score,
    classification_report,
    f1_score,
    recall_score,
    explained_variance_score,
    precision_score
)


# for regression


from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
    ElasticNet,
    BayesianRidge,
    SGDRegressor,
    PassiveAggressiveRegressor
)


from sklearn.tree import (
    DecisionTreeRegressor,
)

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor,
    ExtraTreesRegressor,
    BaggingRegressor
)


from sklearn.svm import(
    SVR,
    LinearSVR
)

from sklearn.neighbors import (
    KNeighborsRegressor,
)

from sklearn.neural_network import (
    MLPRegressor,
    _multilayer_perceptron
)


# for classification
from sklearn.linear_model import (
    LogisticRegression,
    RidgeClassifier,
    Perceptron,
    PassiveAggressiveClassifier,
    SGDClassifier
)

from sklearn.tree import DecisionTreeClassifier


from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier,
    ExtraTreesClassifier,
    BaggingClassifier
)


from sklearn.svm import (
    SVC,
    LinearSVR,
    NuSVC
)


from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import (
    GaussianNB,
    MultinomialNB,
    BernoulliNB,
    CategoricalNB,
    ComplementNB
)

from sklearn.neural_network import MLPClassifier
from sklearn.discriminant_analysis import (
    QuadraticDiscriminantAnalysis,
    LinearDiscriminantAnalysis
)

from sklearn.impute import IterativeImputer

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline


import scipy.stats as stats

from scipy.stats import (
    anderson,
    jarque_bera,
    shapiro,
    normaltest,
    kstest
)

from statsmodels.stats.diagnostic import lilliefors

from scipy.stats import zscore

from sklearn.feature_extraction import FeatureHasher

from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer, TransformedTargetRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.base import BaseEstimator, TransformerMixin

### Loading DataSets

In [2]:
path = os.path.join('..','data','raw','used_cars.csv')
print(path)

..\data\raw\used_cars.csv

In [3]:
df = pd.read_csv(path)

### Basic Initial Inspection

In [4]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.max_colwidth',None)
df.head(1)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"

In [5]:
df.tail(1)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,"$40,000"

In [6]:
df.sample()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
3943,Mercedes-Benz,Sprinter 2500 Standard Roof,2023,"4,000 mi.",Diesel,211.0HP 2.0L 4 Cylinder Engine Diesel Fuel,9-Speed A/T,White,Black,None reported,Yes,"$65,000"

In [7]:
df.describe(include='all')

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
count,4009,4009,4009.000000,4009,3839,4009,4009,4009,4009,3896,3413,4009
unique,57,1898,NaN,2818,7,1146,62,319,156,2,1,1569
top,Ford,M3 Base,NaN,"110,000 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,A/T,Black,Black,None reported,Yes,"$15,000"
freq,386,30,NaN,16,3309,52,1037,905,2025,2910,3413,39
mean,NaN,NaN,2015.515590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,6.104816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1974.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print(f"The memory consumed in RAM is {(df.memory_usage(deep=True)/(1024*1024)).sum():.3f} MB")

The memory consumed in RAM is 0.872 MB

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   str
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   str
dtypes: int64(1), str(11)
memory usage: 892.6 KB

In [10]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [11]:
df['milage']=(
    df['milage']
    .str.replace(',','')
    .str.replace('mi.','')
    .astype(float)
)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   float64
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   str
dtypes: float64(1), int64(1), str(10)
memory usage: 853.2 KB

In [13]:
df['price'] = (
    df['price']
    .astype(str)             
    .str.replace('$', '')    
    .str.replace(',', '')    
    .astype(float)           
)

In [14]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0

In [15]:
df['Accdent_Occured']=(
    df['accident']
    .apply(lambda x: "NO" if x=='None reported' else "YES")
)

In [16]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accdent_Occured
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO

In [17]:
df['Engine_Capacity']=(
    df['engine']
    .str.extract(r'(\d+\.\d+L|\d+L|\d+\.\d+\s+Liter|\d+\s+Liter)')
)

In [18]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accdent_Occured,Engine_Capacity
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES,3.7L
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES,3.8L
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO,3.5 Liter
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO,3.5L
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO,2.0L

In [19]:
df['Horse_Power']=(
    df['engine']
    .str.extract(r'(\d+\.\d+HP|\d+HP)')
)

In [20]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accdent_Occured,Engine_Capacity,Horse_Power
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES,3.7L,300.0HP
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES,3.8L,NaN
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO,3.5 Liter,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO,3.5L,354.0HP
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO,2.0L,NaN

In [21]:
df['Engine_Capacity'] = (
    df['Engine_Capacity']
    .astype(str)  
    .str.replace('Liter', '', regex=False)
    .str.replace('L', '', regex=False)
    .str.strip()  
    .astype(float)  
)

In [22]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accdent_Occured,Engine_Capacity,Horse_Power
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES,3.7,300.0HP
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES,3.8,NaN
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO,3.5,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO,3.5,354.0HP
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO,2.0,NaN

In [23]:
df['Horse_Power']=(
    df['Horse_Power']
    .astype(str)
    .str.replace('HP','')
    .astype(float)
)

In [24]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accdent_Occured,Engine_Capacity,Horse_Power
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES,3.7,300.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES,3.8,NaN
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO,3.5,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO,3.5,354.0
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO,2.0,NaN

### Handling Missing Values

In [25]:
df.isnull().sum()

brand                0
model                0
model_year           0
milage               0
fuel_type          170
engine               0
transmission         0
ext_col              0
int_col              0
accident           113
clean_title        596
price                0
Accdent_Occured      0
Engine_Capacity    219
Horse_Power        808
dtype: int64

In [26]:
missing_info={}
for col in df.columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The columns with the missing percentage are:\n")
for col, per in missing_info.items():
    print(f"{col}:{per}%")

 The columns with the missing percentage are:

fuel_type:4.24%
accident:2.82%
clean_title:14.87%
Engine_Capacity:5.46%
Horse_Power:20.15%

In [27]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accdent_Occured,Engine_Capacity,Horse_Power
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES,3.7,300.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES,3.8,NaN
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO,3.5,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO,3.5,354.0
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO,2.0,NaN

In [28]:
Categorical_columns=df.select_dtypes(include=['object','category']).columns
Numerical_columns= df.select_dtypes(include=['number','int64','int32','float64','float32']).columns

C:\Users\sauju\AppData\Local\Temp\ipykernel_25188\3204705995.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  Categorical_columns=df.select_dtypes(include=['object','category']).columns

In [29]:
df[Categorical_columns].head()

,brand,model,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,Accdent_Occured
0,Ford,Utility Police Interceptor Base,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,YES
1,Hyundai,Palisade SEL,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,YES
2,Lexus,RX 350 RX 350,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,NO
3,INFINITI,Q50 Hybrid Sport,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,NO
4,Audi,Q3 45 S line Premium Plus,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,NO

In [30]:
df[Numerical_columns].head()

   model_year   milage    price  Engine_Capacity  Horse_Power
0        2013  51000.0  10300.0              3.7        300.0
1        2021  34742.0  38005.0              3.8          NaN
2        2022  22372.0  54598.0              3.5          NaN
3        2015  88900.0  15500.0              3.5        354.0
4        2021   9835.0  34999.0              2.0          NaN

In [31]:
missing_info={}
for col in Categorical_columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The categorical columns with the missing percentage are:\n")
for col, per in missing_info.items():
    print(f"{col}:{per}%")

 The categorical columns with the missing percentage are:

fuel_type:4.24%
accident:2.82%
clean_title:14.87%

In [32]:
df['clean_title'].value_counts()

clean_title
Yes    3413
Name: count, dtype: int64

In [33]:
df['clean_title'].head()

0    Yes
1    Yes
2    NaN
3    Yes
4    NaN
Name: clean_title, dtype: str

In [34]:
df['clean_title']= df['clean_title'].fillna('unknown')

In [35]:
df['clean_title'].head()

0        Yes
1        Yes
2    unknown
3        Yes
4    unknown
Name: clean_title, dtype: str

In [36]:
missing_info={}
for col in Categorical_columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The categorical columns with the missing percentage are:\n")
for col, per in missing_info.items():
    print(f"{col}:{per}%")

 The categorical columns with the missing percentage are:

fuel_type:4.24%
accident:2.82%

In [37]:
df[['brand','model','transmission','engine','fuel_type']].head(50)

,brand,model,transmission,engine,fuel_type
0,Ford,Utility Police Interceptor Base,6-Speed A/T,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,E85 Flex Fuel
1,Hyundai,Palisade SEL,8-Speed Automatic,3.8L V6 24V GDI DOHC,Gasoline
2,Lexus,RX 350 RX 350,Automatic,3.5 Liter DOHC,Gasoline
3,INFINITI,Q50 Hybrid Sport,7-Speed A/T,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,Hybrid
4,Audi,Q3 45 S line Premium Plus,8-Speed Automatic,2.0L I4 16V GDI DOHC Turbo,Gasoline
5,Acura,ILX 2.4L,F,2.4 Liter,Gasoline
6,Audi,S3 2.0T Premium Plus,6-Speed A/T,292.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Gasoline
7,BMW,740 iL,A/T,282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Gasoline
8,Lexus,RC 350 F Sport,6-Speed A/T,311.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,Gasoline
9,Tesla,Model X Long Range Plus,A/T,534.0HP Electric Motor Electric Fuel System,NaN
10,Land,Rover Range Rover Sport 3.0 Supercharged HST,Automatic,V6,Gasoline
11,Aston,Martin DBS Superleggera,8-Speed A/T,715.0HP 5.2L 12 Cylinder Engine Gasoline Fuel,Gasoline
12,Toyota,Supra 3.0 Premium,A/T,382.0HP 3.0L Straight 6 Cylinder Engine Gasoline Fuel,Gasoline
13,Lincoln,Aviator Reserve AWD,Transmission w/Dual Shift Mode,400.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Gasoline
14,Jaguar,F-TYPE,Automatic,2.0 Liter Supercharged,Gasoline
15,Land,Rover LR4 HSE,A/T,375.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Gasoline
16,Mercedes-Benz,Metris Base,9-Speed Automatic,2.0L I4 16V GDI DOHC Turbo,Gasoline
17,Dodge,Challenger SXT,A/T,305.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,Gasoline
18,Nissan,350Z Enthusiast,6-Speed M/T,287.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,Gasoline
19,Jaguar,F-TYPE R,8-Speed A/T,550.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Gasoline
20,Genesis,GV70 3.5T Sport,8-Speed A/T,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,Gasoline
21,Chevrolet,S-10 LS,A/T,120.0HP 2.2L 4 Cylinder Engine Flex Fuel Capability,E85 Flex Fuel
22,BMW,440 Gran Coupe 440i xDrive,Automatic,3.0 Liter Turbo,Gasoline
23,Ford,F-150 XLT,Automatic,3.5L V6 24V PDI DOHC Twin Turbo,Gasoline
24,Chevrolet,Suburban RST,10-Speed A/T,355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,Gasoline
25,Hyundai,Elantra N Base,Transmission w/Dual Shift Mode,276.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Gasoline
26,Nissan,Sentra SR,Automatic,1.8 Liter,Gasoline
27,Mercedes-Benz,AMG CLA 45 Base 4MATIC,A/T,382.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Gasoline
28,BMW,650 Gran Coupe i xDrive,8-Speed A/T,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Gasoline
29,Audi,Q5 2.0T Premium Plus,8-Speed Automatic,2.0L I4 16V GDI DOHC Turbo Flexible Fuel,E85 Flex Fuel
30,Mercedes-Benz,AMG C 43 Base 4MATIC,9-Speed A/T,362.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Gasoline
31,Dodge,Ram 1500 Laramie Mega Cab,A/T,345.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,Gasoline
32,BMW,i3 120Ah w/Range Extender,Automatic,120 AH,Hybrid
33,Kia,Sorento SX,A/T,276.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,Gasoline
34,Lexus,LX 570 Base,8-Speed A/T,383.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,Gasoline
35,Jeep,New Compass Trailhawk,A/T,180.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,Gasoline
36,BMW,340 i,Automatic,3.0 Liter Turbo,Gasoline
37,Audi,A4 2.0T Premium Plus quattro,8-Speed A/T,211.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Gasoline
38,Hyundai,Tucson SE,A/T,173.0HP 2.7L V6 Cylinder Engine Gasoline Fuel,Gasoline
39,BMW,Z4 sDrive28i,A/T,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Gasoline
40,Bentley,Continental GTC Base,6-Speed A/T,552.0HP 6.0L 12 Cylinder Engine Flex Fuel Capability,E85 Flex Fuel
41,Honda,Passport Elite,Automatic,3.5 Liter SOHC,Gasoline
42,Dodge,Sprinter 2500,5-Speed A/T,3.0L V6 Cylinder Engine Diesel Fuel,Diesel
43,BMW,M850 i xDrive,Automatic,4.4 Liter DOHC Twin Turbo,Gasoline
44,Lucid,Air Grand Touring,1-Speed A/T,536.0HP Electric Motor Electric Fuel System,NaN
45,Audi,A7 Premium,8-Speed A/T,310.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Gasoline
46,Chevrolet,Silverado 1500 Custom Trail Boss,Automatic,5.3L V8 16V GDI OHV,Gasoline
47,MINI,Convertible John Cooper Works,6-Speed A/T,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Gasoline
48,Toyota,Avalon Touring,A/T,268.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,Gasoline
49,Porsche,Cayenne Platinum Edition,8-Speed A/T,300.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,Gasoline

In [45]:
df.loc[df['engine'].str.contains('Electric Motor Electric Fuel System', case= False, na= False),['brand','model','engine','transmission','fuel_type']]

,brand,model,engine,transmission,fuel_type
9,Tesla,Model X Long Range Plus,534.0HP Electric Motor Electric Fuel System,A/T,NaN
44,Lucid,Air Grand Touring,536.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
68,Lucid,Air Grand Touring,536.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
92,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
122,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,NaN
129,Lucid,Air Pure,620.0HP Electric Motor Electric Fuel System,A/T,NaN
155,Tesla,Model 3 Performance,455.0HP Electric Motor Electric Fuel System,A/T,NaN
189,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
225,Tesla,Model X Base,670.0HP Electric Motor Electric Fuel System,A/T,NaN
253,Mercedes-Benz,EQS 450 4MATIC,355.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
266,Mercedes-Benz,EQS 450+ Base,329.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
298,Tesla,Model 3 Standard Range Plus,271.0HP Electric Motor Electric Fuel System,A/T,NaN
346,Tesla,Model X Long Range,670.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
397,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
410,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
451,Audi,e-tron Prestige,355.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
472,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,NaN
503,Chevrolet,Bolt EUV Premier,200.0HP Electric Motor Electric Fuel System,A/T,NaN
518,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
526,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,NaN
529,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
542,Nissan,Leaf S,147.0HP Electric Motor Electric Fuel System,A/T,NaN
543,Nissan,Leaf SL,107.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
684,Audi,e-tron Prestige,355.0HP Electric Motor Electric Fuel System,A/T,NaN
687,Chevrolet,Bolt EUV Premier,200.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
703,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
719,Karma,Revero Base,403.0HP 2.0L Electric Motor Electric Fuel System,A/T,NaN
721,Ford,Mustang Mach-E California Route 1,290.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
746,Ford,Mustang Mach-E Premium,266.0HP Electric Motor Electric Fuel System,A/T,NaN
752,Ford,Mustang Mach-E Premium,346.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
753,FIAT,500e Battery Electric,111.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
757,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
799,Tesla,Model S 70D,329.0HP Electric Motor Electric Fuel System,A/T,NaN
943,Nissan,Leaf SV PLUS,214.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1008,Volvo,C40 Recharge Pure Electric Twin Ultimate,402.0HP Electric Motor Electric Fuel System,A/T,NaN
1047,Tesla,Model X Long Range Plus,534.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1071,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
1091,Tesla,Model X Base,670.0HP Electric Motor Electric Fuel System,A/T,NaN
1098,BMW,i3 Base w/Range Extender,170.0HP 0.65L Electric Motor Electric Fuel System,1-Speed A/T,NaN
1119,Hyundai,Kona EV SEL,201.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1126,Tesla,Model X P90D,691.0HP Electric Motor Electric Fuel System,A/T,NaN
1139,Kia,EV6 GT-Line,320.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1157,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1203,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1212,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
1230,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
1235,Nissan,Leaf SL,107.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1247,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
1250,Audi,Q4 e-tron Sportback Premium,295.0HP Electric Motor Electric Fuel System,A/T,NaN
1293,Tesla,Model 3 Standard Range Plus,Electric Motor Electric Fuel System,A/T,NaN
1330,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,NaN
1331,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
1509,Hyundai,IONIQ 5 SE,320.0HP Electric Motor Electric Fuel System,A/T,NaN
1522,Ford,F-150 Lightning XLT,563.0HP Electric Motor Electric Fuel System,A/T,NaN
1534,Tesla,Model X 75D,518.0HP Electric Motor Electric Fuel System,A/T,NaN
1544,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1554,Karma,Revero Base,403.0HP 2.0L Electric Motor Electric Fuel System,A/T,NaN
1593,Tesla,Model S P100D,518.0HP Electric Motor Electric Fuel System,A/T,NaN
1598,Tesla,Model X Long Range Plus,557.0HP Electric Motor Electric Fuel System,A/T,NaN
1697,Cadillac,LYRIQ Luxury,500.0HP Electric Motor Electric Fuel System,A/T,NaN
1709,Tesla,Model S P100D,518.0HP Electric Motor Electric Fuel System,A/T,NaN
1788,Tesla,Model S 85D,422.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1836,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,NaN
1884,Tesla,Model 3 Performance,271.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1888,Tesla,Model S 100D,518.0HP Electric Motor Electric Fuel System,A/T,NaN
1901,Tesla,Model S Performance,778.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
1911,Porsche,Taycan Turbo,616.0HP Electric Motor Electric Fuel System,A/T,NaN
1943,Tesla,Model 3 Standard Range Plus,Electric Motor Electric Fuel System,A/T,NaN
2066,Chevrolet,Bolt EV LT,200.0HP Electric Motor Electric Fuel System,A/T,NaN
2102,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,A/T,NaN
2116,Tesla,Model S P100D,Electric Motor Electric Fuel System,1-Speed A/T,NaN
2124,Tesla,Model X Long Range,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2181,Tesla,Model 3 Base,271.0HP Electric Motor Electric Fuel System,A/T,NaN
2184,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2191,Tesla,Model 3 Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2209,Tesla,Model 3 Standard Range Plus,Electric Motor Electric Fuel System,A/T,NaN
2231,Tesla,Model 3 Long Range,Electric Motor Electric Fuel System,A/T,NaN
2233,Rivian,R1T Launch Edition,835.0HP Electric Motor Electric Fuel System,A/T,NaN
2236,Tesla,Model 3 Mid Range,271.0HP Electric Motor Electric Fuel System,A/T,NaN
2250,Tesla,Model 3 Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
2322,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,NaN
2343,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2345,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
2407,Rivian,R1S Adventure Package,533.0HP Electric Motor Electric Fuel System,A/T,NaN
2426,Volkswagen,ID.4 Pro S,295.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2451,Tesla,Model S Long Range,670.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2472,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2484,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,NaN
2492,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2677,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,NaN
2770,Kia,Niro EV EX,201.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2772,Porsche,Taycan Base,321.0HP Electric Motor Electric Fuel System,2-Speed A/T,NaN
2779,Tesla,Model S Performance,416.0HP Electric Motor Electric Fuel System,A/T,NaN
2795,Mercedes-Benz,EQS 450+ Base,329.0HP Electric Motor Electric Fuel System,A/T,NaN
2870,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,NaN
2877,Tesla,Model X P100D,Electric Motor Electric Fuel System,1-Speed A/T,NaN
2952,Ford,Mustang Mach-E Premium,346.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2956,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
2964,Hyundai,Kona EV SEL,201.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
2979,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,NaN
2982,Tesla,Model S 85,362.0HP Electric Motor Electric Fuel System,A/T,NaN
2984,Tesla,Model 3 Standard Range,271.0HP Electric Motor Electric Fuel System,A/T,NaN
3033,Porsche,Taycan Base,375.0HP Electric Motor Electric Fuel System,A/T,NaN
3048,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3061,Tesla,Model 3 Long Range,Electric Motor Electric Fuel System,A/T,NaN
3090,BMW,i3 120Ah w/Range Extender,170.0HP 0.65L Electric Motor Electric Fuel System,A/T,NaN
3109,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,NaN
3128,Tesla,Model S 100D,Electric Motor Electric Fuel System,1-Speed A/T,NaN
3134,Tesla,Model X 75D,518.0HP Electric Motor Electric Fuel System,A/T,NaN
3151,Tesla,Model S Long Range Plus,557.0HP Electric Motor Electric Fuel System,A/T,NaN
3164,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3168,Volkswagen,e-Golf SE,115.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3169,Tesla,Model X Long Range,670.0HP Electric Motor Electric Fuel System,A/T,NaN
3193,Tesla,Model X 75D,518.0HP Electric Motor Electric Fuel System,A/T,NaN
3196,Tesla,Model X Long Range,670.0HP Electric Motor Electric Fuel System,A/T,NaN
3207,Kia,EV6 GT-Line,320.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3224,Ford,Mustang Mach-E GT,480.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3255,BMW,i3 Base,170.0HP 0.65L Electric Motor Electric Fuel System,1-Speed A/T,NaN
3272,Tesla,Model S Long Range,670.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3314,Tesla,Model S 75D,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3324,BMW,i3 Base w/Range Extender,170.0HP 0.65L Electric Motor Electric Fuel System,A/T,NaN
3383,Tesla,Model 3 Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3399,Tesla,Model X 100D,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3417,Porsche,Taycan Base,375.0HP Electric Motor Electric Fuel System,2-Speed A/T,NaN
3425,Tesla,Model X Plaid,1020.0HP Electric Motor Electric Fuel System,A/T,NaN
3427,Tesla,Model S 100D,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3468,BMW,i3 94 Ah,170.0HP 0.65L Electric Motor Electric Fuel System,1-Speed A/T,NaN
3502,Ford,Mustang Mach-E GT,480.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3510,Tesla,Model S Plaid,1020.0HP Electric Motor Electric Fuel System,A/T,NaN
3520,Chevrolet,Bolt EV LT,200.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3557,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3618,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3647,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3673,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3682,Tesla,Model S 90D,417.0HP Electric Motor Electric Fuel System,A/T,NaN
3709,Ford,Mustang Mach-E Select,266.0HP Electric Motor Electric Fuel System,A/T,NaN
3739,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,A/T,NaN
3764,Audi,Q4 e-tron 50 Premium Plus,295.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3768,GMC,HUMMER EV Edition 1,Electric Motor Electric Fuel System,A/T,NaN
3783,Porsche,Taycan 4S,482.0HP Electric Motor Electric Fuel System,2-Speed A/T,NaN
3813,Ford,Mustang Mach-E GT,480.0HP Electric Motor Electric Fuel System,A/T,NaN
3834,Ford,F-150 Lightning LARIAT,563.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3896,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,NaN
3906,Tesla,Model 3 Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,NaN
3913,Tesla,Model S 100D,518.0HP Electric Motor Electric Fuel System,A/T,NaN
3932,Tesla,Model X Performance,778.0HP Electric Motor Electric Fuel System,A/T,NaN

In [58]:
df['fuel_type']= df['fuel_type'].where(~df['engine'].str.contains('ELectric Motor Electric Fuel System',case=False,na=False),df['fuel_type'].fillna('Electric'))

In [59]:
df.loc[df['engine'].str.contains('Electric Motor Electric Fuel System', case= False, na= False),['brand','model','engine','transmission','fuel_type']]

,brand,model,engine,transmission,fuel_type
9,Tesla,Model X Long Range Plus,534.0HP Electric Motor Electric Fuel System,A/T,Electric
44,Lucid,Air Grand Touring,536.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
68,Lucid,Air Grand Touring,536.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
92,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
122,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
129,Lucid,Air Pure,620.0HP Electric Motor Electric Fuel System,A/T,Electric
155,Tesla,Model 3 Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
189,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
225,Tesla,Model X Base,670.0HP Electric Motor Electric Fuel System,A/T,Electric
253,Mercedes-Benz,EQS 450 4MATIC,355.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
266,Mercedes-Benz,EQS 450+ Base,329.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
298,Tesla,Model 3 Standard Range Plus,271.0HP Electric Motor Electric Fuel System,A/T,Electric
346,Tesla,Model X Long Range,670.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
397,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
410,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
451,Audi,e-tron Prestige,355.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
472,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
503,Chevrolet,Bolt EUV Premier,200.0HP Electric Motor Electric Fuel System,A/T,Electric
518,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
526,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
529,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
542,Nissan,Leaf S,147.0HP Electric Motor Electric Fuel System,A/T,Electric
543,Nissan,Leaf SL,107.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
684,Audi,e-tron Prestige,355.0HP Electric Motor Electric Fuel System,A/T,Electric
687,Chevrolet,Bolt EUV Premier,200.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
703,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
719,Karma,Revero Base,403.0HP 2.0L Electric Motor Electric Fuel System,A/T,Electric
721,Ford,Mustang Mach-E California Route 1,290.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
746,Ford,Mustang Mach-E Premium,266.0HP Electric Motor Electric Fuel System,A/T,Electric
752,Ford,Mustang Mach-E Premium,346.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
753,FIAT,500e Battery Electric,111.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
757,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
799,Tesla,Model S 70D,329.0HP Electric Motor Electric Fuel System,A/T,Electric
943,Nissan,Leaf SV PLUS,214.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1008,Volvo,C40 Recharge Pure Electric Twin Ultimate,402.0HP Electric Motor Electric Fuel System,A/T,Electric
1047,Tesla,Model X Long Range Plus,534.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1071,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
1091,Tesla,Model X Base,670.0HP Electric Motor Electric Fuel System,A/T,Electric
1098,BMW,i3 Base w/Range Extender,170.0HP 0.65L Electric Motor Electric Fuel System,1-Speed A/T,Electric
1119,Hyundai,Kona EV SEL,201.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1126,Tesla,Model X P90D,691.0HP Electric Motor Electric Fuel System,A/T,Electric
1139,Kia,EV6 GT-Line,320.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1157,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1203,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1212,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
1230,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
1235,Nissan,Leaf SL,107.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1247,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
1250,Audi,Q4 e-tron Sportback Premium,295.0HP Electric Motor Electric Fuel System,A/T,Electric
1293,Tesla,Model 3 Standard Range Plus,Electric Motor Electric Fuel System,A/T,Electric
1330,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
1331,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
1509,Hyundai,IONIQ 5 SE,320.0HP Electric Motor Electric Fuel System,A/T,Electric
1522,Ford,F-150 Lightning XLT,563.0HP Electric Motor Electric Fuel System,A/T,Electric
1534,Tesla,Model X 75D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
1544,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1554,Karma,Revero Base,403.0HP 2.0L Electric Motor Electric Fuel System,A/T,Electric
1593,Tesla,Model S P100D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
1598,Tesla,Model X Long Range Plus,557.0HP Electric Motor Electric Fuel System,A/T,Electric
1697,Cadillac,LYRIQ Luxury,500.0HP Electric Motor Electric Fuel System,A/T,Electric
1709,Tesla,Model S P100D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
1788,Tesla,Model S 85D,422.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1836,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
1884,Tesla,Model 3 Performance,271.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1888,Tesla,Model S 100D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
1901,Tesla,Model S Performance,778.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1911,Porsche,Taycan Turbo,616.0HP Electric Motor Electric Fuel System,A/T,Electric
1943,Tesla,Model 3 Standard Range Plus,Electric Motor Electric Fuel System,A/T,Electric
2066,Chevrolet,Bolt EV LT,200.0HP Electric Motor Electric Fuel System,A/T,Electric
2102,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,A/T,Electric
2116,Tesla,Model S P100D,Electric Motor Electric Fuel System,1-Speed A/T,Electric
2124,Tesla,Model X Long Range,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2181,Tesla,Model 3 Base,271.0HP Electric Motor Electric Fuel System,A/T,Electric
2184,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2191,Tesla,Model 3 Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2209,Tesla,Model 3 Standard Range Plus,Electric Motor Electric Fuel System,A/T,Electric
2231,Tesla,Model 3 Long Range,Electric Motor Electric Fuel System,A/T,Electric
2233,Rivian,R1T Launch Edition,835.0HP Electric Motor Electric Fuel System,A/T,Electric
2236,Tesla,Model 3 Mid Range,271.0HP Electric Motor Electric Fuel System,A/T,Electric
2250,Tesla,Model 3 Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
2322,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
2343,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2345,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
2407,Rivian,R1S Adventure Package,533.0HP Electric Motor Electric Fuel System,A/T,Electric
2426,Volkswagen,ID.4 Pro S,295.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2451,Tesla,Model S Long Range,670.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2472,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2484,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
2492,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2677,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
2770,Kia,Niro EV EX,201.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2772,Porsche,Taycan Base,321.0HP Electric Motor Electric Fuel System,2-Speed A/T,Electric
2779,Tesla,Model S Performance,416.0HP Electric Motor Electric Fuel System,A/T,Electric
2795,Mercedes-Benz,EQS 450+ Base,329.0HP Electric Motor Electric Fuel System,A/T,Electric
2870,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
2877,Tesla,Model X P100D,Electric Motor Electric Fuel System,1-Speed A/T,Electric
2952,Ford,Mustang Mach-E Premium,346.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2956,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
2964,Hyundai,Kona EV SEL,201.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2979,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
2982,Tesla,Model S 85,362.0HP Electric Motor Electric Fuel System,A/T,Electric
2984,Tesla,Model 3 Standard Range,271.0HP Electric Motor Electric Fuel System,A/T,Electric
3033,Porsche,Taycan Base,375.0HP Electric Motor Electric Fuel System,A/T,Electric
3048,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3061,Tesla,Model 3 Long Range,Electric Motor Electric Fuel System,A/T,Electric
3090,BMW,i3 120Ah w/Range Extender,170.0HP 0.65L Electric Motor Electric Fuel System,A/T,Electric
3109,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
3128,Tesla,Model S 100D,Electric Motor Electric Fuel System,1-Speed A/T,Electric
3134,Tesla,Model X 75D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
3151,Tesla,Model S Long Range Plus,557.0HP Electric Motor Electric Fuel System,A/T,Electric
3164,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3168,Volkswagen,e-Golf SE,115.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3169,Tesla,Model X Long Range,670.0HP Electric Motor Electric Fuel System,A/T,Electric
3193,Tesla,Model X 75D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
3196,Tesla,Model X Long Range,670.0HP Electric Motor Electric Fuel System,A/T,Electric
3207,Kia,EV6 GT-Line,320.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3224,Ford,Mustang Mach-E GT,480.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3255,BMW,i3 Base,170.0HP 0.65L Electric Motor Electric Fuel System,1-Speed A/T,Electric
3272,Tesla,Model S Long Range,670.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3314,Tesla,Model S 75D,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3324,BMW,i3 Base w/Range Extender,170.0HP 0.65L Electric Motor Electric Fuel System,A/T,Electric
3383,Tesla,Model 3 Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3399,Tesla,Model X 100D,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3417,Porsche,Taycan Base,375.0HP Electric Motor Electric Fuel System,2-Speed A/T,Electric
3425,Tesla,Model X Plaid,1020.0HP Electric Motor Electric Fuel System,A/T,Electric
3427,Tesla,Model S 100D,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3468,BMW,i3 94 Ah,170.0HP 0.65L Electric Motor Electric Fuel System,1-Speed A/T,Electric
3502,Ford,Mustang Mach-E GT,480.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3510,Tesla,Model S Plaid,1020.0HP Electric Motor Electric Fuel System,A/T,Electric
3520,Chevrolet,Bolt EV LT,200.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3557,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3618,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3647,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3673,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3682,Tesla,Model S 90D,417.0HP Electric Motor Electric Fuel System,A/T,Electric
3709,Ford,Mustang Mach-E Select,266.0HP Electric Motor Electric Fuel System,A/T,Electric
3739,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,A/T,Electric
3764,Audi,Q4 e-tron 50 Premium Plus,295.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3768,GMC,HUMMER EV Edition 1,Electric Motor Electric Fuel System,A/T,Electric
3783,Porsche,Taycan 4S,482.0HP Electric Motor Electric Fuel System,2-Speed A/T,Electric
3813,Ford,Mustang Mach-E GT,480.0HP Electric Motor Electric Fuel System,A/T,Electric
3834,Ford,F-150 Lightning LARIAT,563.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3896,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
3906,Tesla,Model 3 Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3913,Tesla,Model S 100D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
3932,Tesla,Model X Performance,778.0HP Electric Motor Electric Fuel System,A/T,Electric

In [62]:
missing_info={}
for col in Categorical_columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The categorical columns with the missing percentage are:\n")
for col, per in missing_info.items():
    print(f"{col}:{per}%")

 The categorical columns with the missing percentage are:

accident:2.82%

In [65]:
df.loc[df['engine'].str.contains('Electric Motor Electric Fuel System', case= False, na= False),['brand','model','engine','transmission','fuel_type']]

,brand,model,engine,transmission,fuel_type
9,Tesla,Model X Long Range Plus,534.0HP Electric Motor Electric Fuel System,A/T,Electric
44,Lucid,Air Grand Touring,536.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
68,Lucid,Air Grand Touring,536.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
92,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
122,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
129,Lucid,Air Pure,620.0HP Electric Motor Electric Fuel System,A/T,Electric
155,Tesla,Model 3 Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
189,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
225,Tesla,Model X Base,670.0HP Electric Motor Electric Fuel System,A/T,Electric
253,Mercedes-Benz,EQS 450 4MATIC,355.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
266,Mercedes-Benz,EQS 450+ Base,329.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
298,Tesla,Model 3 Standard Range Plus,271.0HP Electric Motor Electric Fuel System,A/T,Electric
346,Tesla,Model X Long Range,670.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
397,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
410,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
451,Audi,e-tron Prestige,355.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
472,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
503,Chevrolet,Bolt EUV Premier,200.0HP Electric Motor Electric Fuel System,A/T,Electric
518,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
526,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
529,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
542,Nissan,Leaf S,147.0HP Electric Motor Electric Fuel System,A/T,Electric
543,Nissan,Leaf SL,107.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
684,Audi,e-tron Prestige,355.0HP Electric Motor Electric Fuel System,A/T,Electric
687,Chevrolet,Bolt EUV Premier,200.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
703,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
719,Karma,Revero Base,403.0HP 2.0L Electric Motor Electric Fuel System,A/T,Electric
721,Ford,Mustang Mach-E California Route 1,290.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
746,Ford,Mustang Mach-E Premium,266.0HP Electric Motor Electric Fuel System,A/T,Electric
752,Ford,Mustang Mach-E Premium,346.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
753,FIAT,500e Battery Electric,111.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
757,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
799,Tesla,Model S 70D,329.0HP Electric Motor Electric Fuel System,A/T,Electric
943,Nissan,Leaf SV PLUS,214.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1008,Volvo,C40 Recharge Pure Electric Twin Ultimate,402.0HP Electric Motor Electric Fuel System,A/T,Electric
1047,Tesla,Model X Long Range Plus,534.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1071,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
1091,Tesla,Model X Base,670.0HP Electric Motor Electric Fuel System,A/T,Electric
1098,BMW,i3 Base w/Range Extender,170.0HP 0.65L Electric Motor Electric Fuel System,1-Speed A/T,Electric
1119,Hyundai,Kona EV SEL,201.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1126,Tesla,Model X P90D,691.0HP Electric Motor Electric Fuel System,A/T,Electric
1139,Kia,EV6 GT-Line,320.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1157,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1203,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1212,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
1230,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
1235,Nissan,Leaf SL,107.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1247,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
1250,Audi,Q4 e-tron Sportback Premium,295.0HP Electric Motor Electric Fuel System,A/T,Electric
1293,Tesla,Model 3 Standard Range Plus,Electric Motor Electric Fuel System,A/T,Electric
1330,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
1331,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
1509,Hyundai,IONIQ 5 SE,320.0HP Electric Motor Electric Fuel System,A/T,Electric
1522,Ford,F-150 Lightning XLT,563.0HP Electric Motor Electric Fuel System,A/T,Electric
1534,Tesla,Model X 75D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
1544,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1554,Karma,Revero Base,403.0HP 2.0L Electric Motor Electric Fuel System,A/T,Electric
1593,Tesla,Model S P100D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
1598,Tesla,Model X Long Range Plus,557.0HP Electric Motor Electric Fuel System,A/T,Electric
1697,Cadillac,LYRIQ Luxury,500.0HP Electric Motor Electric Fuel System,A/T,Electric
1709,Tesla,Model S P100D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
1788,Tesla,Model S 85D,422.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1836,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
1884,Tesla,Model 3 Performance,271.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1888,Tesla,Model S 100D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
1901,Tesla,Model S Performance,778.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
1911,Porsche,Taycan Turbo,616.0HP Electric Motor Electric Fuel System,A/T,Electric
1943,Tesla,Model 3 Standard Range Plus,Electric Motor Electric Fuel System,A/T,Electric
2066,Chevrolet,Bolt EV LT,200.0HP Electric Motor Electric Fuel System,A/T,Electric
2102,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,A/T,Electric
2116,Tesla,Model S P100D,Electric Motor Electric Fuel System,1-Speed A/T,Electric
2124,Tesla,Model X Long Range,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2181,Tesla,Model 3 Base,271.0HP Electric Motor Electric Fuel System,A/T,Electric
2184,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2191,Tesla,Model 3 Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2209,Tesla,Model 3 Standard Range Plus,Electric Motor Electric Fuel System,A/T,Electric
2231,Tesla,Model 3 Long Range,Electric Motor Electric Fuel System,A/T,Electric
2233,Rivian,R1T Launch Edition,835.0HP Electric Motor Electric Fuel System,A/T,Electric
2236,Tesla,Model 3 Mid Range,271.0HP Electric Motor Electric Fuel System,A/T,Electric
2250,Tesla,Model 3 Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
2322,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
2343,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2345,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
2407,Rivian,R1S Adventure Package,533.0HP Electric Motor Electric Fuel System,A/T,Electric
2426,Volkswagen,ID.4 Pro S,295.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2451,Tesla,Model S Long Range,670.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2472,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2484,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
2492,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2677,Rivian,R1S Adventure Package,835.0HP Electric Motor Electric Fuel System,A/T,Electric
2770,Kia,Niro EV EX,201.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2772,Porsche,Taycan Base,321.0HP Electric Motor Electric Fuel System,2-Speed A/T,Electric
2779,Tesla,Model S Performance,416.0HP Electric Motor Electric Fuel System,A/T,Electric
2795,Mercedes-Benz,EQS 450+ Base,329.0HP Electric Motor Electric Fuel System,A/T,Electric
2870,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
2877,Tesla,Model X P100D,Electric Motor Electric Fuel System,1-Speed A/T,Electric
2952,Ford,Mustang Mach-E Premium,346.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2956,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
2964,Hyundai,Kona EV SEL,201.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
2979,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
2982,Tesla,Model S 85,362.0HP Electric Motor Electric Fuel System,A/T,Electric
2984,Tesla,Model 3 Standard Range,271.0HP Electric Motor Electric Fuel System,A/T,Electric
3033,Porsche,Taycan Base,375.0HP Electric Motor Electric Fuel System,A/T,Electric
3048,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3061,Tesla,Model 3 Long Range,Electric Motor Electric Fuel System,A/T,Electric
3090,BMW,i3 120Ah w/Range Extender,170.0HP 0.65L Electric Motor Electric Fuel System,A/T,Electric
3109,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,A/T,Electric
3128,Tesla,Model S 100D,Electric Motor Electric Fuel System,1-Speed A/T,Electric
3134,Tesla,Model X 75D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
3151,Tesla,Model S Long Range Plus,557.0HP Electric Motor Electric Fuel System,A/T,Electric
3164,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3168,Volkswagen,e-Golf SE,115.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3169,Tesla,Model X Long Range,670.0HP Electric Motor Electric Fuel System,A/T,Electric
3193,Tesla,Model X 75D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
3196,Tesla,Model X Long Range,670.0HP Electric Motor Electric Fuel System,A/T,Electric
3207,Kia,EV6 GT-Line,320.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3224,Ford,Mustang Mach-E GT,480.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3255,BMW,i3 Base,170.0HP 0.65L Electric Motor Electric Fuel System,1-Speed A/T,Electric
3272,Tesla,Model S Long Range,670.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3314,Tesla,Model S 75D,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3324,BMW,i3 Base w/Range Extender,170.0HP 0.65L Electric Motor Electric Fuel System,A/T,Electric
3383,Tesla,Model 3 Performance,455.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3399,Tesla,Model X 100D,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3417,Porsche,Taycan Base,375.0HP Electric Motor Electric Fuel System,2-Speed A/T,Electric
3425,Tesla,Model X Plaid,1020.0HP Electric Motor Electric Fuel System,A/T,Electric
3427,Tesla,Model S 100D,518.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3468,BMW,i3 94 Ah,170.0HP 0.65L Electric Motor Electric Fuel System,1-Speed A/T,Electric
3502,Ford,Mustang Mach-E GT,480.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3510,Tesla,Model S Plaid,1020.0HP Electric Motor Electric Fuel System,A/T,Electric
3520,Chevrolet,Bolt EV LT,200.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3557,Rivian,R1S Launch Edition,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3618,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3647,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3673,Tesla,Model Y Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3682,Tesla,Model S 90D,417.0HP Electric Motor Electric Fuel System,A/T,Electric
3709,Ford,Mustang Mach-E Select,266.0HP Electric Motor Electric Fuel System,A/T,Electric
3739,Tesla,Model 3 Long Range,271.0HP Electric Motor Electric Fuel System,A/T,Electric
3764,Audi,Q4 e-tron 50 Premium Plus,295.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3768,GMC,HUMMER EV Edition 1,Electric Motor Electric Fuel System,A/T,Electric
3783,Porsche,Taycan 4S,482.0HP Electric Motor Electric Fuel System,2-Speed A/T,Electric
3813,Ford,Mustang Mach-E GT,480.0HP Electric Motor Electric Fuel System,A/T,Electric
3834,Ford,F-150 Lightning LARIAT,563.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3896,Tesla,Model Y Performance,455.0HP Electric Motor Electric Fuel System,A/T,Electric
3906,Tesla,Model 3 Long Range,425.0HP Electric Motor Electric Fuel System,1-Speed A/T,Electric
3913,Tesla,Model S 100D,518.0HP Electric Motor Electric Fuel System,A/T,Electric
3932,Tesla,Model X Performance,778.0HP Electric Motor Electric Fuel System,A/T,Electric

In [66]:
missing_info={}
for col in Categorical_columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The categorical columns with the missing percentage are:\n")
for col, per in missing_info.items():
    print(f"{col}:{per}%")

 The categorical columns with the missing percentage are:

accident:2.82%